version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  build:
    macos:
      xcode: 14.2.0
    steps:
    - run:
        name: Sign Studio
        command: |
          mkdir -p DIST/convertigo-15061-develop-8.2.0-beta
          date > DIST/convertigo-15061-develop-8.2.0-beta/date.txt
    - aws-s3/sync:
        arguments: --help
        from: DIST
        to: 's3://convertigo-ci'