version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  build:
    macos:
      xcode: 14.2.0
    steps:
    - aws-cli/setup
    - run:
        name: Sign Studio
        command: |
          export C8O_VERSION=convertigo-15079-develop-8.2.0-beta
          security create-keychain -p "" ~/Library/Keychains/MyKeychain.keychain
          security default-keychain -s ~/Library/Keychains/MyKeychain.keychain
          security unlock-keychain -p "" ~/Library/Keychains/MyKeychain.keychain
          security set-keychain-settings -t 7200 -l ~/Library/Keychains/MyKeychain.keychain
          security list-keychains -d user
          echo "${APPLE_CERT_DEV_ID_APP_BASE64}" | base64 -D -o DevIdApplication.p12
          echo "${APPLE_CERT_DEV_ID_INS_BASE64}" | base64 -D -o DevIdInstaller.p12
          security import ./DevIdApplication.p12 -k ~/Library/Keychains/MyKeychain.keychain -P "${APPLE_CERT_PASSWORD}" -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
          security import ./DevIdInstaller.p12 -k ~/Library/Keychains/MyKeychain.keychain -P "${APPLE_CERT_PASSWORD}" -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
          security find-identity -p codesigning
          security set-key-partition-list -S apple-tool:,apple: -s -k '' ~/Library/Keychains/MyKeychain.keychain
          
          mkdir -p DIST/${C8O_VERSION}
           
          wget https://convertigo-ci.s3-eu-west-3.amazonaws.com/${C8O_VERSION}/convertigo-studio-8.2.0-beta-macosx-arm.tar.gz
          tar -xf convertigo-studio-8.2.0-beta-macosx-arm.tar.gz
          sed -e "s,.studio<,.studio.arm64<," -i.bak convertigo-studio-8.2.0-beta-macosx-arm/ConvertigoStudio.app/Contents/Info.plist
          rm convertigo-studio-8.2.0-beta-macosx-arm/ConvertigoStudio.app/Contents/Info.plist.bak
          codesign --entitlements entitlements.plist --options=runtime --deep -vvv -f --sign "Developer ID Application: Convertigo (${APPLE_TEAM_ID})"  convertigo-studio-8.2.0-beta-macosx-arm/ConvertigoStudio.app
          productbuild --component convertigo-studio-8.2.0-beta-macosx-arm/ConvertigoStudio.app "/Applications" --sign "Developer ID Installer: Convertigo (${APPLE_TEAM_ID})" DIST/${C8O_VERSION}/convertigo-studio-8.2.0-beta-macosx-arm.pkg
          
          wget https://convertigo-ci.s3-eu-west-3.amazonaws.com/${C8O_VERSION}/convertigo-studio-8.2.0-beta-macosx.tar.gz
          tar -xf convertigo-studio-8.2.0-beta-macosx.tar.gz
          sed -e "s,.studio<,.studio.x86_64<," -i.bak convertigo-studio-8.2.0-beta-macosx/ConvertigoStudio.app/Contents/Info.plist
          rm convertigo-studio-8.2.0-beta-macosx/ConvertigoStudio.app/Contents/Info.plist.bak
          codesign --entitlements entitlements.plist --options=runtime --deep -vvv -f --sign "Developer ID Application: Convertigo (${APPLE_TEAM_ID})"  convertigo-studio-8.2.0-beta-macosx/ConvertigoStudio.app
          productbuild --component convertigo-studio-8.2.0-beta-macosx/ConvertigoStudio.app "/Applications" --sign "Developer ID Installer: Convertigo (${APPLE_TEAM_ID})" DIST/${C8O_VERSION}/convertigo-studio-8.2.0-beta-macosx-x86_64.pkg
          
          xcrun notarytool submit DIST/${C8O_VERSION}/convertigo-studio-8.2.0-beta-macosx-arm.pkg --apple-id "${APPLE_ID}" --password "${APPLE_PASSWORD}" --team-id "${APPLE_TEAM_ID}"
          xcrun notarytool submit DIST/${C8O_VERSION}/convertigo-studio-8.2.0-beta-macosx-x86_64.pkg --apple-id "${APPLE_ID}" --password "${APPLE_PASSWORD}" --team-id "${APPLE_TEAM_ID}"
          
          aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read DIST s3://convertigo-ci/